### ISSUE TITLE
mSupply Docs Menu Overlaps Content

### ISSUE THREAD

**Issue by kahn-msupply** [openmsupply/msupply_docs#11]
## Issue Found

mSupply Docs website menu is overlapping content (as shown in screenshot). Tested on Chrome, Edge, and Safari. All showing the same issue.

## Screenshot

<img width="1425" alt="Screen Shot 2023-08-18 at 11 07 54 AM" src="https://github.com/openmsupply/msupply_docs/assets/132425100/1c83c8f0-9e3a-451d-a062-1e9f160d48a9">

**Comment by kahn-msupply** [comment]
Issue is related to screen size, as working fine on 15.6" laptop, until I reduce the webpage size.

**Comment by mark-prins** [comment]
even at 'normal' height, the menu bar overlays the content:

![image](https://github.com/openmsupply/msupply_docs/assets/9192912/c6f40367-23e0-4fcc-a550-e23b75b28629)

In which case, I don't see what needs to be changed.

My concern is that at small screen widths, but not so small that the menu collapses, the search disappears:

![image](https://github.com/openmsupply/msupply_docs/assets/9192912/b4b4fc5d-3c1a-44d1-8b78-3810f7d7280f)

**Comment by mark-prins** [comment]
updated nav styles
