### ISSUE TITLE
Docs should provide heading link(s) similar to the old user guide 

### ISSUE THREAD

**Issue by DamonRusden** [openmsupply/msupply_docs#7]
![image](https://user-images.githubusercontent.com/122417327/216231157-44fc34a9-c127-4e4b-b3f2-4101d1d4e13a.png)

This would streamline the linking process for headings in the docs, a benefit to support team and editors

**Comment by jmbrunskill** [comment]
@DamonRusden it turns out this can be done by adding this to the `_index.md`

`insert_anchor_links = "right"`

See docs here:https://github.com/getzola/zola/blob/master/docs/content/documentation/content/section.md

```
# This determines whether to insert a link for each header like the ones you can see on this site if you hover over
# a header.
# The default template can be overridden by creating an `anchor-link.html` file in the `templates` directory.
# This value can be "left", "right", "heading" or "none".
# "heading" means the full heading becomes the text of the anchor.
insert_anchor_links = "none"
```

**Comment by jmbrunskill** [comment]
We'd probably want to tweak the template or styling as well, I'm guessing Mark or Anisha would be the best people to look at how to make it look pretty :)
https://github.com/getzola/zola/blob/master/components/templates/src/builtins/anchor-link.html

**Comment by Chris-Petty** [comment]
I can see us editing docs and pretty easily breaking links in the application - wondering if we could set up a tester or linter that checks all the external URLs in omSupply code?

**Comment by mark-prins** [comment]
I think a tweak to the styling is required. This is how it looks if you enable the links:

![image](https://user-images.githubusercontent.com/9192912/216507332-a33d5470-081d-4166-a7d7-2f1e33d24c81.png)

**Comment by mark-prins** [comment]
added to docs and pushed out. have gone with the hover to be slightly more refined.
